# Generated by Django 4.1 on 2022-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='country',
            field=models.CharField(default='Norway', max_length=255),
        ),
    ]
