# Generated by Django 4.1 on 2022-08-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_firm_website_client_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='construction_equipement',
            new_name='construction_county',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='expected_completion_date',
            new_name='project_comp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='construction_site',
        ),
        migrations.AddField(
            model_name='project',
            name='construction_address',
            field=models.CharField(default='149 name street', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='construction_postal',
            field=models.CharField(default='00000', max_length=6),
        ),
        migrations.AddField(
            model_name='project',
            name='country_abr',
            field=models.CharField(default='MX', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='project_design',
            field=models.FileField(default='design.dwt', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_overview',
            field=models.FileField(default='overview.pdf', upload_to=''),
        ),
    ]
