# Generated by Django 4.1 on 2022-08-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_construction_equipement_project_construction_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
