# Generated by Django 4.1 on 2022-08-08 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_architect_computer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='design_file',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.project'),
        ),
    ]
