# Generated by Django 4.1 on 2022-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_client_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='address',
            field=models.CharField(default='address', max_length=255),
            preserve_default=False,
        ),
    ]
