# Generated by Django 4.1 on 2022-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_firm_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
