# Generated by Django 4.1 on 2022-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_firm_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'ordering': ['id']},
        ),
    ]
